<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>perfectoneObj1</name>
   <tag></tag>
   <elementGuidId>8d93936e-8dd5-456c-881b-8c4c8d506751</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>reer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>perfectoneObj2</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
</WebElementEntity>
